services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cafe-everywhere-api
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    ports:
      - '127.0.0.1:9999:9999'


networks:
  default:
    name: cafe-everywhere
    external: true
